/**
 * Binary STL generator for printOKAY keyring configurator.
 *
 * Generates two STL files for 2-color printing in BambuStudio:
 *   base.stl  — the keyring body (0 → BASE_HEIGHT_MM)
 *   text.stl  — the raised text letters (BASE_HEIGHT_MM → TOTAL_HEIGHT_MM)
 *
 * Import both into BambuStudio as multi-part object, assign filament colors.
 */

import type { KeyringConfig, KeyringSizeOption } from "./keyring";
import { getShapePolygon } from "./keyring";
import { extractTextContours } from "./textpaths";
import { computeTextShape, holePolygon, findHoleCenter } from "./textshape";

// ─── Print geometry constants ─────────────────────────────────────────────────

const BASE_HEIGHT_MM  = 2.4;   // keyring body height
const TEXT_HEIGHT_MM  = 0.6;   // raised text above body
const TOTAL_HEIGHT_MM = BASE_HEIGHT_MM + TEXT_HEIGHT_MM;
const HOLE_RADIUS_MM  = 4;     // ring attachment hole

// ─── STL types ────────────────────────────────────────────────────────────────

type Vec3 = [number, number, number];
type Tri  = [Vec3, Vec3, Vec3]; // winding order: counter-clockwise = outward normal

// ─── Binary STL encoder ──────────────────────────────────────────────────────

function encodeStl(triangles: Tri[]): Buffer {
  const buf = Buffer.alloc(80 + 4 + triangles.length * 50);
  buf.write("printOKAY Keyring — generated by printokay.dk", 0, "utf8");
  buf.writeUInt32LE(triangles.length, 80);
  let off = 84;
  for (const [a, b, c] of triangles) {
    // Compute face normal
    const ux = b[0]-a[0], uy = b[1]-a[1], uz = b[2]-a[2];
    const vx = c[0]-a[0], vy = c[1]-a[1], vz = c[2]-a[2];
    const nx = uy*vz - uz*vy;
    const ny = uz*vx - ux*vz;
    const nz = ux*vy - uy*vx;
    const nl = Math.sqrt(nx*nx + ny*ny + nz*nz) || 1;
    buf.writeFloatLE(nx/nl, off);   buf.writeFloatLE(ny/nl, off+4); buf.writeFloatLE(nz/nl, off+8);
    off += 12;
    for (const v of [a, b, c]) {
      buf.writeFloatLE(v[0], off); buf.writeFloatLE(v[1], off+4); buf.writeFloatLE(v[2], off+8);
      off += 12;
    }
    buf.writeUInt16LE(0, off); off += 2;
  }
  return buf;
}

// ─── Polygon helpers ──────────────────────────────────────────────────────────

type P2 = { x: number; y: number };

/** Ensure polygon is counter-clockwise (positive area = CCW in Y-up coords). */
function ensureCCW(poly: P2[]): P2[] {
  let area = 0;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    area += (poly[j].x + poly[i].x) * (poly[j].y - poly[i].y);
  }
  // area > 0 → CW in screen coords → CCW in Y-up → correct for bottom face outward normals
  // For top face we reverse
  return area > 0 ? poly : [...poly].reverse();
}

/** Ensure polygon is clockwise. */
function ensureCW(poly: P2[]): P2[] {
  const ccw = ensureCCW(poly);
  return [...ccw].reverse();
}

// ─── 3D geometry builders ────────────────────────────────────────────────────

/**
 * Triangulate a flat polygon (with optional holes) using earcut.
 * Returns vertex array + triangle index array.
 */
function triangulate2D(
  outer: P2[],
  holes: P2[][] = []
): { verts: P2[]; indices: number[] } {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { default: earcut } = require("earcut");

  const allVerts: P2[] = [...outer];
  const holeStarts: number[] = [];
  for (const hole of holes) {
    holeStarts.push(allVerts.length);
    allVerts.push(...hole);
  }
  const flatCoords = allVerts.flatMap((p) => [p.x, p.y]);
  const indices: number[] = earcut(flatCoords, holeStarts.length ? holeStarts : undefined);
  return { verts: allVerts, indices };
}

/**
 * Create bottom face triangles (z = zVal, normals pointing down).
 * Polygon must be CW when viewed from below (= CCW top-down).
 */
function bottomFace(outer: P2[], holes: P2[][], zVal: number): Tri[] {
  const { verts, indices } = triangulate2D(ensureCCW(outer), holes.map(ensureCW));
  const tris: Tri[] = [];
  for (let i = 0; i < indices.length; i += 3) {
    const a = verts[indices[i]];
    const b = verts[indices[i+1]];
    const c = verts[indices[i+2]];
    // Reverse winding for downward normal
    tris.push([[c.x,c.y,zVal],[b.x,b.y,zVal],[a.x,a.y,zVal]]);
  }
  return tris;
}

/**
 * Create top face triangles (z = zVal, normals pointing up).
 */
function topFace(outer: P2[], holes: P2[][], zVal: number): Tri[] {
  const { verts, indices } = triangulate2D(ensureCCW(outer), holes.map(ensureCW));
  const tris: Tri[] = [];
  for (let i = 0; i < indices.length; i += 3) {
    const a = verts[indices[i]];
    const b = verts[indices[i+1]];
    const c = verts[indices[i+2]];
    tris.push([[a.x,a.y,zVal],[b.x,b.y,zVal],[c.x,c.y,zVal]]);
  }
  return tris;
}

/**
 * Create side wall triangles for a polygon extruded from zBottom to zTop.
 * outward = true → outward-facing normals (for outer perimeter).
 * outward = false → inward-facing normals (for hole perimeter).
 */
function sideWalls(poly: P2[], zBottom: number, zTop: number, outward = true): Tri[] {
  const tris: Tri[] = [];
  const n = poly.length;
  for (let i = 0; i < n; i++) {
    const a = poly[i];
    const b = poly[(i + 1) % n];
    if (outward) {
      tris.push([[a.x,a.y,zBottom],[b.x,b.y,zBottom],[b.x,b.y,zTop]]);
      tris.push([[a.x,a.y,zBottom],[b.x,b.y,zTop],  [a.x,a.y,zTop]]);
    } else {
      tris.push([[b.x,b.y,zBottom],[a.x,a.y,zBottom],[a.x,a.y,zTop]]);
      tris.push([[b.x,b.y,zBottom],[a.x,a.y,zTop],  [b.x,b.y,zTop]]);
    }
  }
  return tris;
}

/**
 * Extrude a polygon (with holes) into a solid 3D prism.
 * Combines bottom face + top face + outer side walls + hole side walls.
 */
function extrudeSolid(
  outer: P2[],
  holes: P2[][],
  zBottom: number,
  zTop: number
): Tri[] {
  return [
    ...bottomFace(outer, holes, zBottom),
    ...topFace(outer, holes, zTop),
    ...sideWalls(ensureCCW(outer), zBottom, zTop, true),
    ...holes.flatMap((h) => sideWalls(ensureCCW(h), zBottom, zTop, false)),
  ];
}

// ─── Main STL generator ───────────────────────────────────────────────────────

export type KeyringStlResult = {
  baseStl: Buffer;
  textStl: Buffer;
};

export async function generateKeyringStl(
  config: KeyringConfig,
  size: KeyringSizeOption
): Promise<KeyringStlResult> {

  // 1. Extract text contours from font
  const fontSize = config.fontSize > 0 ? config.fontSize : Math.min(size.widthMm, size.heightMm) * 0.4;
  const textContours = extractTextContours(config.text, config.font, fontSize);

  // 2. Compute keyring outline shape
  let shapePoly: P2[];
  if (config.shapeType === "auto") {
    const marginMm = Math.min(size.widthMm, size.heightMm) * 0.15;
    shapePoly = computeTextShape(
      textContours,
      marginMm,
      size.widthMm,
      size.heightMm
    );
  } else {
    shapePoly = getShapePolygon(config.shapeType, size.widthMm, size.heightMm);
  }

  // 3. Compute hole position (top center of the shape)
  const { cx: holeCx, cy: holeCy } = findHoleCenter(shapePoly, HOLE_RADIUS_MM);
  const hole = holePolygon(holeCx, holeCy, HOLE_RADIUS_MM);

  // 4. Generate base STL (keyring body with ring hole)
  const baseTris = extrudeSolid(shapePoly, [hole], 0, BASE_HEIGHT_MM);
  const baseStl = encodeStl(baseTris);

  // 5. Generate text STL (raised letters on top of base)
  // Filter to contours that are inside the keyring shape (sanity check)
  const textTris: Tri[] = [];
  for (const contour of textContours) {
    if (contour.length < 3) continue;
    // Ensure the contour represents a filled region (not a counter-shape like hole in 'O')
    // We include all contours — earcut handles outer/inner automatically via winding
    try {
      textTris.push(...extrudeSolid(contour, [], BASE_HEIGHT_MM, TOTAL_HEIGHT_MM));
    } catch {
      // Skip malformed contours silently
    }
  }
  const textStl = encodeStl(textTris);

  return { baseStl, textStl };
}
