/**
 * Binary STL generator for printOKAY keyring configurator.
 *
 * Generates two STL files for 2-color printing in BambuStudio:
 *   base.stl  — the keyring body (0 → BASE_HEIGHT_MM) with ring hole
 *   text.stl  — the raised text letters (BASE_HEIGHT_MM → TOTAL_HEIGHT_MM)
 *
 * Coordinate convention throughout this file:
 *   X/Y in mm, Y-axis points UP (math convention, matching opentype.js after Y-flip)
 *   Z is print height. STL outward normals use right-hand CCW winding.
 *
 * After the Y-flip in textpaths.ts:
 *   - Outer letter contours are CCW in Y-up → signedArea > 0
 *   - Inner counter-shapes (holes in 'O', 'A', etc.) are CW → signedArea < 0
 */

import type { KeyringConfig, KeyringSizeOption } from "./keyring";
import { getShapePolygon } from "./keyring";
import { extractTextContours } from "./textpaths";
import { computeTextShape, holePolygon, findHoleCenter } from "./textshape";

// ─── Print geometry constants ─────────────────────────────────────────────────

const BASE_HEIGHT_MM  = 2.4;   // keyring body height
const TEXT_HEIGHT_MM  = 0.6;   // raised text above body
const TOTAL_HEIGHT_MM = BASE_HEIGHT_MM + TEXT_HEIGHT_MM;
const HOLE_RADIUS_MM  = 3.0;   // ring attachment hole radius
const TAB_RADIUS_MM   = HOLE_RADIUS_MM + 2.0; // circular tab that merges with text bubble
const TAB_CLEARANCE_MM = 1.5;  // gap between top of text and bottom of tab circle

// ─── STL types ────────────────────────────────────────────────────────────────

type Vec3 = [number, number, number];
type Tri  = [Vec3, Vec3, Vec3];

// ─── Binary STL encoder ──────────────────────────────────────────────────────

function encodeStl(triangles: Tri[]): Buffer {
  const buf = Buffer.alloc(80 + 4 + triangles.length * 50);
  buf.write("printOKAY Keyring — generated by printokay.dk", 0, "utf8");
  buf.writeUInt32LE(triangles.length, 80);
  let off = 84;
  for (const [a, b, c] of triangles) {
    const ux = b[0]-a[0], uy = b[1]-a[1], uz = b[2]-a[2];
    const vx = c[0]-a[0], vy = c[1]-a[1], vz = c[2]-a[2];
    const nx = uy*vz - uz*vy;
    const ny = uz*vx - ux*vz;
    const nz = ux*vy - uy*vx;
    const nl = Math.sqrt(nx*nx + ny*ny + nz*nz) || 1;
    buf.writeFloatLE(nx/nl, off);   buf.writeFloatLE(ny/nl, off+4); buf.writeFloatLE(nz/nl, off+8);
    off += 12;
    for (const v of [a, b, c]) {
      buf.writeFloatLE(v[0], off); buf.writeFloatLE(v[1], off+4); buf.writeFloatLE(v[2], off+8);
      off += 12;
    }
    buf.writeUInt16LE(0, off); off += 2;
  }
  return buf;
}

// ─── Polygon math ─────────────────────────────────────────────────────────────

type P2 = { x: number; y: number };

/**
 * Standard shoelace signed area.
 * Positive → CCW in Y-up (math convention).
 * Negative → CW in Y-up.
 */
function signedArea(poly: P2[]): number {
  let a = 0;
  const n = poly.length;
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    a += poly[i].x * poly[j].y - poly[j].x * poly[i].y;
  }
  return a / 2;
}

/** Make polygon CCW in Y-up (positive shoelace area). */
function ensureCCW(poly: P2[]): P2[] {
  return signedArea(poly) > 0 ? poly : [...poly].reverse();
}

/** Make polygon CW in Y-up (negative shoelace area). */
function ensureCW(poly: P2[]): P2[] {
  return signedArea(poly) < 0 ? poly : [...poly].reverse();
}

/**
 * Ray-cast point-in-polygon test.
 * Returns true if point p is inside polygon poly.
 */
function pointInPolygon(p: P2, poly: P2[]): boolean {
  let inside = false;
  const n = poly.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const xi = poly[i].x, yi = poly[i].y;
    const xj = poly[j].x, yj = poly[j].y;
    if ((yi > p.y) !== (yj > p.y) &&
        p.x < ((xj - xi) * (p.y - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

// ─── 3D geometry builders ────────────────────────────────────────────────────

/** Triangulate a 2D polygon with holes using earcut. */
function triangulate2D(outer: P2[], holes: P2[][] = []): { verts: P2[]; indices: number[] } {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const earcut = require("earcut").default ?? require("earcut");

  const allVerts: P2[] = [...outer];
  const holeStarts: number[] = [];
  for (const hole of holes) {
    holeStarts.push(allVerts.length);
    allVerts.push(...hole);
  }
  const flatCoords = allVerts.flatMap((p) => [p.x, p.y]);
  const indices: number[] = earcut(flatCoords, holeStarts.length ? holeStarts : undefined);
  return { verts: allVerts, indices };
}

/**
 * Bottom face (z = zVal, normals pointing −Z).
 * Earcut with CCW outer / CW holes, then reverse winding for downward normal.
 */
function bottomFace(outer: P2[], holes: P2[][], zVal: number): Tri[] {
  const { verts, indices } = triangulate2D(ensureCCW(outer), holes.map(ensureCW));
  const tris: Tri[] = [];
  for (let i = 0; i < indices.length; i += 3) {
    const a = verts[indices[i]], b = verts[indices[i+1]], c = verts[indices[i+2]];
    // Reverse winding → normal points down (−Z)
    tris.push([[c.x,c.y,zVal],[b.x,b.y,zVal],[a.x,a.y,zVal]]);
  }
  return tris;
}

/**
 * Top face (z = zVal, normals pointing +Z).
 * Earcut with CCW outer / CW holes, keep winding for upward normal.
 */
function topFace(outer: P2[], holes: P2[][], zVal: number): Tri[] {
  const { verts, indices } = triangulate2D(ensureCCW(outer), holes.map(ensureCW));
  const tris: Tri[] = [];
  for (let i = 0; i < indices.length; i += 3) {
    const a = verts[indices[i]], b = verts[indices[i+1]], c = verts[indices[i+2]];
    tris.push([[a.x,a.y,zVal],[b.x,b.y,zVal],[c.x,c.y,zVal]]);
  }
  return tris;
}

/**
 * Side walls for a polygon perimeter extruded from zBottom to zTop.
 *
 * Call with a CCW polygon for outward-facing normals (outer boundary of solid).
 * Call with a CCW polygon + outward=false to get inward-facing normals (hole cavity wall).
 *
 * We always accept a CCW polygon and flip winding when outward=false.
 */
function sideWalls(poly: P2[], zBottom: number, zTop: number, outward: boolean): Tri[] {
  const ccw = ensureCCW(poly);
  const tris: Tri[] = [];
  const n = ccw.length;
  for (let i = 0; i < n; i++) {
    const a = ccw[i];
    const b = ccw[(i + 1) % n];
    if (outward) {
      // CCW polygon, outward: a_bot → b_bot → b_top and a_bot → b_top → a_top
      tris.push([[a.x,a.y,zBottom],[b.x,b.y,zBottom],[b.x,b.y,zTop]]);
      tris.push([[a.x,a.y,zBottom],[b.x,b.y,zTop],  [a.x,a.y,zTop]]);
    } else {
      // Flip winding for inward normals (hole cavity)
      tris.push([[b.x,b.y,zBottom],[a.x,a.y,zBottom],[a.x,a.y,zTop]]);
      tris.push([[b.x,b.y,zBottom],[a.x,a.y,zTop],  [b.x,b.y,zTop]]);
    }
  }
  return tris;
}

/**
 * Extrude a closed polygon (with optional holes) into a watertight solid prism.
 * outer and holes must be in the Y-up coordinate system.
 * Produces correct outward normals on all faces.
 */
function extrudeSolid(outer: P2[], holes: P2[][], zBottom: number, zTop: number): Tri[] {
  return [
    ...bottomFace(outer, holes, zBottom),
    ...topFace(outer, holes, zTop),
    ...sideWalls(outer, zBottom, zTop, true),
    // Hole walls: CCW polygon with inward normals
    ...holes.flatMap(h => sideWalls(h, zBottom, zTop, false)),
  ];
}

// ─── Text contour grouping ───────────────────────────────────────────────────

type ContourGroup = { outer: P2[]; holes: P2[][] };

/**
 * Given a flat list of font contours (outer letters + their counter-holes),
 * group them into { outer, holes[] } pairs ready for extrusion.
 *
 * After Y-flip in textpaths.ts:
 *   outer contours  → CCW → signedArea > 0
 *   counter-shapes  → CW  → signedArea < 0
 */
function groupTextContours(contours: P2[][]): ContourGroup[] {
  const outers = contours.filter(c => c.length >= 3 && signedArea(c) > 0);
  const inners = contours.filter(c => c.length >= 3 && signedArea(c) < 0);

  const groups: ContourGroup[] = outers.map(o => ({ outer: o, holes: [] }));

  // Assign each inner contour to the smallest outer that contains it
  for (const inner of inners) {
    const testPt = inner[0];
    // Find all outers containing this inner, then pick smallest area (closest parent)
    let bestIdx = -1;
    let bestArea = Infinity;
    for (let i = 0; i < outers.length; i++) {
      if (pointInPolygon(testPt, outers[i])) {
        const a = Math.abs(signedArea(outers[i]));
        if (a < bestArea) { bestArea = a; bestIdx = i; }
      }
    }
    if (bestIdx >= 0) groups[bestIdx].holes.push(inner);
  }

  return groups;
}

// ─── Circular tab for ring attachment ────────────────────────────────────────

/**
 * Create a circle polygon in Y-up coords (CCW = positive area).
 * Used as both the tab shape (for merging into the bubble) and the hole.
 */
function circlePolygon(cx: number, cy: number, r: number, steps = 48): P2[] {
  return Array.from({ length: steps }, (_, i) => {
    const t = (i / steps) * 2 * Math.PI;
    return { x: cx + r * Math.cos(t), y: cy + r * Math.sin(t) };
  });
}

// ─── Main STL generator ───────────────────────────────────────────────────────

export type KeyringStlResult = { baseStl: Buffer; textStl: Buffer };

export async function generateKeyringStl(
  config: KeyringConfig,
  size: KeyringSizeOption
): Promise<KeyringStlResult> {

  // 1. Extract raw text contours (Y-flipped, mm units, centered in X)
  const fontSize = config.fontSize > 0
    ? config.fontSize
    : Math.min(size.widthMm, size.heightMm) * 0.45;

  const rawContours = extractTextContours(config.text, config.font, fontSize);

  // 2. Build keyring outline shape and determine hole position
  let shapePoly: P2[];
  let holeCX: number;
  let holeCY: number;

  if (config.shapeType === "auto") {
    // Compute a circular "tab" above the text.
    // The tab is merged into the bubble shape via clipper union so there is
    // always a solid nub for the ring hole — regardless of text length or shape.
    const textPoints = rawContours.flat();
    const textTopY    = textPoints.length > 0 ? Math.max(...textPoints.map(p => p.y)) : 0;
    const textCenterX = 0; // text is always horizontally centered in X

    // Tab center sits TAB_RADIUS + clearance above the tallest letter
    const tabCY    = textTopY + TAB_RADIUS_MM + TAB_CLEARANCE_MM;
    const tabCircle = circlePolygon(textCenterX, tabCY, TAB_RADIUS_MM);

    // Only pass outer letter contours to clipper — counter-shapes (holes in 'O', 'A' etc.)
    // must be excluded so the offset doesn't create unwanted dents in the bubble.
    const outerContours = rawContours.filter(c => c.length >= 3 && signedArea(c) > 0);
    const marginMm = Math.min(size.widthMm, size.heightMm) * 0.15;

    shapePoly = computeTextShape(
      [...outerContours, tabCircle],
      marginMm,
      size.widthMm,
      size.heightMm
    );

    holeCX = textCenterX;
    holeCY = tabCY;
  } else {
    // Heart / oval: predefined template shapes.
    shapePoly = getShapePolygon(config.shapeType, size.widthMm, size.heightMm);
    // Place hole at the top-center of the template shape.
    const hc = findHoleCenter(shapePoly, HOLE_RADIUS_MM);
    holeCX = hc.cx;
    holeCY = hc.cy;
  }

  // 3. Ring attachment hole polygon (subtracts from base)
  const holePoly = circlePolygon(holeCX, holeCY, HOLE_RADIUS_MM);

  // 4. Generate base.stl: solid prism from 0 → BASE_HEIGHT_MM with hole cutout
  const baseTris = extrudeSolid(shapePoly, [holePoly], 0, BASE_HEIGHT_MM);
  const baseStl  = encodeStl(baseTris);

  // 5. Generate text.stl: raised letters from BASE_HEIGHT_MM → TOTAL_HEIGHT_MM.
  //    Group contours into outer-with-holes to correctly handle 'O', 'A', 'P' etc.
  const contourGroups = groupTextContours(rawContours);
  const textTris: Tri[] = [];
  for (const { outer, holes } of contourGroups) {
    try {
      textTris.push(...extrudeSolid(outer, holes, BASE_HEIGHT_MM, TOTAL_HEIGHT_MM));
    } catch {
      // skip malformed contour groups
    }
  }
  const textStl = encodeStl(textTris);

  return { baseStl, textStl };
}
